### ISSUE TITLE
Generate command fails with SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by avichalp** [danielquinn/pyletheia#3]
Running `generate` commands gives error.

`aletheia generate`

Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/aletheia", line 7, in <module>
    from aletheia.cli import Command
  File "/Library/Python/2.7/site-packages/aletheia/cli.py", line 73
SyntaxError: Non-ASCII character '\xf0' in file /Library/Python/2.7/site-packages/aletheia/cli.py on line 73, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I believe this is related to the unicode char here:

https://github.com/danielquinn/pyletheia/blob/39317a1b5e90bfff2ab2cd78b2706f2cfdcfb27d/aletheia/cli.py#L72-L74

**Comment by danielquinn** [comment]
Oooh, yeah you tried to run Aletheia in Python 2.  That's not gonna work ;-)  Support is in there for 3.5+, and I may port it to 2.7, but for now, it's not supported, sorry.

**Comment by danielquinn** [comment]
Of course, now that I look back over the docs, I see that *I didn't mention which versions are supported*.  The only place it's explicit is in `setup.cfg` so.... sorry about that.  I'll keep this issue open as a TODO to add that limitation to the docs.

**Comment by danielquinn** [comment]
Alright, [I've patched the documentation](https://aletheia-project.readthedocs.io/en/latest/setup.html#requirements) and included the fact that you need `libmagic`.  I took a guess and assumed that you had to install it with Homebrew, so if that's not the case, please let me know and I'll change it.

**Comment by avichalp** [comment]
Thanks for the update. Yes, I used homebrew to install `libmagic`. :)

**Comment by danielquinn** [comment]
Cool beans!  Closing now :-)
